# wrangler.toml
# 
# An interim wrangler.toml to use for CI testing, until we dynamically
# create the KV stores and route uniquely for each CI test invocation.

# The name of your Workers application
name = "saltmine-ci"

# Your Cloudflare account ID
account_id = "18ff2b4e6205b938652998cfca0d8cff"

# Your Cloudflare zone ID
zone_id = "88b74327b34a5c07ebea8b37b548acf6"

# The route pattern your Workers application will be served at
route = "saltmine-ci.holohost.net/*"

# The kind of application you're deploying to Cloudflare
type = "javascript"

# To disable publishing to your workers.dev subdomain,
# set private = true in your wrangler.toml
private = true

## kv namespace bindings
[[kv-namespaces]]
binding = "SALTMINE"
id = "a39cef90a1524efe83fc995e3196b3a8"
