# wrangler.toml

# The name of your Workers application
name = "saltmine"

# Your Cloudflare account ID
account_id = "18ff2b4e6205b938652998cfca0d8cff"

# Your Cloudflare zone ID
zone_id = "88b74327b34a5c07ebea8b37b548acf6"

# The route pattern your Workers application will be served at
route = "saltmine.holohost.net/*"

# The kind of application you're deploying to Cloudflare
type = "javascript"

# To disable publishing to your workers.dev subdomain,
# set private = true in your wrangler.toml
private = true

## kv namespace bindings
[[kv-namespaces]]
binding = "EMAIL_TOKEN_STORE"
id = "9e7baffb76ae4ce8aa929d7591fba1ea"

[[kv-namespaces]]
binding = "SALTMINE"
id = "6a9c312d85cc48278a9d50a584d8e32d"
